# Generated by Django 6.0.2 on 2026-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_chat_admin_chat_avatar_chat_is_group_chat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat_voices/'),
        ),
    ]
