# Generated by Django 6.0.2 on 2026-03-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.person'),
        ),
    ]
