# Generated by Django 6.0.2 on 2026-03-18 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ducks',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'absnt'), (1, 'present'), (2, 'late')], default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LessonDuck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ducks_given', to='education.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
