# Generated by Django 6.0.2 on 2026-03-18 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lesson_theme_student_coins_student_ducks_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.PositiveSmallIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='education.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_marks', to='education.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
