# Generated by Django 6.0.2 on 2026-03-08 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='curator',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Curator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studygroup'),
        ),
        migrations.AddField(
            model_name='task',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studygroup'),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.tasktype'),
        ),
    ]
