# Generated by Django 6.0.2 on 2026-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lessonmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_group',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='qualified_teachers', to='education.subject'),
        ),
    ]
