# Generated by Django 6.0.2 on 2026-04-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_lessontype_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecked',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.attachmentgroup'),
        ),
        migrations.AddField(
            model_name='taskchecked',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
