# Generated by Django 6.0.2 on 2026-04-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_taskchecked_attachments_taskchecked_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
    ]
